import { test, expect } from '@playwright/test';
test('wizard stays readable through every step and produces tasks without rewards', async ({page}, info) => {
  await page.emulateMedia({colorScheme:'dark'});
  await page.goto('/');
  await page.getByRole('button',{name:'Schedule wizard',exact:true}).click();
  const wizard=page.locator('.ops-wizard');
  await expect(wizard).toHaveCSS('background-color','rgb(255, 255, 255)');
  await expect(wizard.getByRole('heading')).toHaveCSS('color','rgb(29, 41, 57)');
  await expect(page.getByLabel('What time do you wake up?')).toBeVisible();
  await page.screenshot({path:info.outputPath('wizard.png'),fullPage:true});
  await wizard.getByRole('button',{name:'Next',exact:true}).click();
  await expect(page.getByLabel('Task name 1', {exact:true})).toBeVisible();
  await wizard.getByRole('button',{name:'Next',exact:true}).click();
  await expect(wizard.getByRole('heading')).toHaveText('Priority tasks');
  await wizard.getByRole('button',{name:'Next',exact:true}).click();
  await wizard.getByRole('button',{name:'Add weekly event'}).click();
  await page.getByLabel('Event name 1').fill('Review');
  await expect(wizard.getByText(/coins/i)).toHaveCount(0);
  await wizard.getByRole('button',{name:'Generate schedule'}).click();
  await wizard.getByRole('button',{name:'Use this schedule'}).click();
  await page.getByRole('button',{name:'Generate scheduled tasks'}).click();
  await page.getByRole('button',{name:'Timeline',exact:true}).click();
  await expect(page.locator('.ops-bar').filter({hasText:'Task:'}).first()).toBeVisible();
  await expect(page.getByRole('button',{name:'Rewards',exact:true})).toHaveCount(0);
});
test('variable templates disable their default and ignore stale amounts on create and edit', async ({page}) => {
  await page.goto('/'); await page.getByRole('button',{name:'Budget',exact:true}).click();
  await page.getByLabel('Expense template').fill('Variable bill');
  await page.getByLabel('Default amount',{exact:true}).fill('999');
  await page.getByLabel('Enter amount each month').check();
  await expect(page.getByLabel('Default amount',{exact:true})).toBeDisabled();
  await page.getByRole('button',{name:'Add template',exact:true}).click();
  await page.getByText('Edit Variable bill',{exact:true}).click();
  await expect(page.getByLabel('Template amount',{exact:true})).toHaveValue('0.00');
  await expect(page.getByLabel('Template amount',{exact:true})).toBeDisabled();
  await page.getByLabel('Variable amount',{exact:true}).uncheck();
  await expect(page.getByLabel('Template amount',{exact:true})).toBeEnabled();
  await page.getByLabel('Template amount',{exact:true}).fill('123');
  await page.getByLabel('Variable amount',{exact:true}).check();
  await page.getByRole('button',{name:'Save template',exact:true}).click();
  await page.reload(); await page.getByRole('button',{name:'Budget',exact:true}).click();
  await page.getByText('Edit Variable bill',{exact:true}).click();
  await expect(page.getByLabel('Template amount',{exact:true})).toHaveValue('0.00');
});
test('date entry validates Gregorian dates and task changes are reflected once on timeline', async ({page}) => {
  await page.goto('/');
  await page.getByLabel('Task date',{exact:true}).fill('2026/02/30');
  await page.getByLabel('Task title',{exact:true}).fill('Dated task');
  await page.getByRole('button',{name:'Add task',exact:true}).click();
  await expect(page.getByText('Dated task (30 min)',{exact:true})).toHaveCount(0);
  await page.getByLabel('Task date',{exact:true}).fill('2026/09/28');
  await page.getByRole('button',{name:'Add task',exact:true}).click();
  await page.getByText('Edit Dated task',{exact:true}).click();
  await page.getByLabel('Revised task title').fill('Updated task');
  await page.getByLabel('Revised task date').fill('2026/09/29');
  await page.getByRole('button',{name:'Save task',exact:true}).click();
  await page.getByLabel('Task date',{exact:true}).fill('2026/09/29');
  await page.getByLabel('Updated task (30 min)').click();
  await expect(page.getByLabel('Updated task (30 min)')).toBeChecked();
  await page.getByRole('button',{name:'Timeline',exact:true}).click();
  await expect(page.locator('.ops-bar').filter({hasText:'Task: Updated task'})).toHaveCount(1);
  await expect(page.getByText('Task: Updated task · 2026/09/29 · 30 min · Completed',{exact:true})).toBeVisible();
  await page.getByRole('button',{name:'Move task Updated task back one day'}).click();
  await page.getByRole('button',{name:'Tasks',exact:true}).click();
  await page.getByLabel('Task date',{exact:true}).fill('2026/09/28');
  await page.getByRole('button',{name:'Delete Updated task',exact:true}).click();
  await page.getByRole('button',{name:'Timeline',exact:true}).click();
  await expect(page.locator('.ops-bar')).toHaveCount(0);
});
test('Timebank and calculator have separate inputs and results', async ({page}) => {
  await page.goto('/'); await page.getByRole('button',{name:'Timebank',exact:true}).click();
  await page.getByLabel('First arrival',{exact:true}).fill('08:00');
  await page.getByLabel('First exit',{exact:true}).fill('12:00');
  await page.getByLabel('Second arrival',{exact:true}).fill('13:00');
  await page.getByLabel('As-of time',{exact:true}).fill('15:00');
  await page.getByLabel('Opening balance (signed minutes or HH:MM)').fill('30');
  await page.getByRole('button',{name:'Calculate remaining time'}).click();
  await expect(page.getByRole('status')).toContainText('01:30');
  await expect(page.getByRole('status')).toContainText('16:30');
  await page.getByLabel('Work date', {exact:true}).fill('2026/02/30');
  await page.getByRole('button', {name:'Clear / new day'}).click();
  expect(await page.getByLabel('Work date', {exact:true}).evaluate((input: HTMLInputElement) => input.checkValidity())).toBe(true);
  await page.getByRole('button',{name:'Time Calculator',exact:true}).click();
  await expect(page.getByLabel('Opening balance (signed minutes or HH:MM)')).toHaveCount(0);
  await page.getByLabel('Start time',{exact:true}).fill('22:00');
  await page.getByLabel('End time',{exact:true}).fill('06:00');
  await page.getByLabel('Break (minutes or HH:MM)').fill('30');
  await page.getByRole('button',{name:'Calculate duration'}).click();
  await expect(page.getByRole('status')).toContainText('07:30');
});
